---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: ''
  ConfigChange:
    Possible: {}
    PossibleNot:
      Ticket:
        Queue:
        - Postmaster
        - Raw
        - Junk
  ConfigMatch:
    Properties:
      Frontend:
        Action:
        - AgentTicketPhone
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: ''
  ID: 3
  Name: AAA Default - New Phone-Ticket
  StopAfterMatch: 0
  ValidID: 1
