---
- ChangeBy: '2'
  ChangeTime: 2018-05-21 22:22:17
  Comment: default closed notification to customer
  CreateBy: '1'
  CreateTime: 2018-05-12 19:22:07
  Data:
    AgentEnabledByDefault:
    - Email
    ArticleAttachmentInclude:
    - '0'
    Events:
    - TicketStateUpdate
    IsVisibleForCustomer:
    - '1'
    LanguageID:
    - en
    QueueID:
    - '1'
    - '2'
    - '4'
    Recipients:
    - Customer
    StateID:
    - '2'
    - '3'
    TransportEmailTemplate:
    - Default
    Transports:
    - Email
    VisibleForAgent:
    - '0'
  ID: '16'
  Message:
    en:
      Body: 'Dear &lt;OTRS_CUSTOMER_REALNAME&gt;,<br />

        <br />

        your ticket with the case number &lt;OTRS_TICKET_TicketNumber&gt; has been
        &lt;OTRS_TICKET_State&gt;.<br />

        If you have anymore questions and want to open the ticket again, reply to
        this message as follow-up.<br />

        <br />

        Ticket link:<br />

        <a href="http://&lt;OTRS_CONFIG_FQDN&gt;/&lt;OTRS_CONFIG_ScriptAlias&gt;customer.pl?Action=CustomerTicketZoom&amp;TicketID=&lt;OTRS_TICKET_TicketID&gt;">&lt;OTRS_CONFIG_HttpType&gt;://&lt;OTRS_CONFIG_FQDN&gt;/&lt;OTRS_CONFIG_ScriptAlias&gt;customer.pl?Action=CustomerTicketZoom&amp;TicketID=&lt;OTRS_TICKET_TicketID&gt;</a>

        <p><br />

        Kind regards,<br />

        Mayer GmbH</p>'
      ContentType: text/html
      Subject: Ticket closed '<OTRS_TICKET_Title>'
  Name: Ticket closed
  ValidID: '1'
