---
- ChangeBy: '2'
  ChangeTime: 2018-03-25 18:40:42
  Comment: default closed notification to customer
  CreateBy: '1'
  CreateTime: 2018-03-23 16:16:04
  Data:
    AgentEnabledByDefault:
    - Email
    ArticleAttachmentInclude:
    - '0'
    Events:
    - TicketStateUpdate
    IsVisibleForCustomer:
    - '1'
    LanguageID:
    - en
    QueueID:
    - '1'
    - '2'
    - '4'
    - '11'
    - '12'
    - '13'
    - '14'
    - '15'
    - '16'
    - '17'
    - '18'
    - '19'
    - '20'
    - '21'
    - '22'
    - '23'
    - '24'
    - '25'
    - '26'
    - '27'
    - '28'
    - '29'
    - '30'
    - '31'
    Recipients:
    - Customer
    StateID:
    - '2'
    - '3'
    TransportEmailTemplate:
    - Default
    Transports:
    - Email
    VisibleForAgent:
    - '0'
  ID: '16'
  Message:
    en:
      Body: 'Dear &lt;OTRS_CUSTOMER_REALNAME&gt;,<br />

        <br />

        your ticket with the case number &lt;OTRS_TICKET_TicketNumber&gt;
        has been &lt;OTRS_TICKET_State&gt;.<br />

        <br />

        If you have anymore questions and want to open the ticket again, reply to
        this message as follow-up.<br />
        <br />

        Ticket link:<br />

        <a href="http://&lt;OTRS_CONFIG_FQDN&gt;/&lt;OTRS_CONFIG_ScriptAlias&gt;customer.pl?Action=CustomerTicketZoom&amp;TicketID=&lt;OTRS_TICKET_TicketID&gt;">&lt;OTRS_CONFIG_HttpType&gt;://&lt;OTRS_CONFIG_FQDN&gt;/&lt;OTRS_CONFIG_ScriptAlias&gt;customer.pl?Action=CustomerTicketZoom&amp;TicketID=&lt;OTRS_TICKET_TicketID&gt;</a>


        <br />

        Kind regards,<br />

        Support - Mayer GmbH'
      ContentType: text/html
      Subject: Ticket closed '<OTRS_TICKET_Title>'
  Name: Ticket closed
  ValidID: '1'
