var annotated_dup =
[
    [ "Database", "namespace_database.html", [
      [ "DataService", "class_database_1_1_data_service.html", "class_database_1_1_data_service" ],
      [ "Highscore", "class_database_1_1_highscore.html", "class_database_1_1_highscore" ],
      [ "HighscoreManager", "class_database_1_1_highscore_manager.html", "class_database_1_1_highscore_manager" ],
      [ "Skins", "class_database_1_1_skins.html", null ]
    ] ],
    [ "SQLite4Unity3d", "namespace_s_q_lite4_unity3d.html", [
      [ "AutoIncrementAttribute", "class_s_q_lite4_unity3d_1_1_auto_increment_attribute.html", null ],
      [ "BaseTableQuery", "class_s_q_lite4_unity3d_1_1_base_table_query.html", "class_s_q_lite4_unity3d_1_1_base_table_query" ],
      [ "CollationAttribute", "class_s_q_lite4_unity3d_1_1_collation_attribute.html", null ],
      [ "ColumnAttribute", "class_s_q_lite4_unity3d_1_1_column_attribute.html", null ],
      [ "IgnoreAttribute", "class_s_q_lite4_unity3d_1_1_ignore_attribute.html", null ],
      [ "IndexedAttribute", "class_s_q_lite4_unity3d_1_1_indexed_attribute.html", null ],
      [ "MaxLengthAttribute", "class_s_q_lite4_unity3d_1_1_max_length_attribute.html", null ],
      [ "NotNullAttribute", "class_s_q_lite4_unity3d_1_1_not_null_attribute.html", null ],
      [ "NotNullConstraintViolationException", "class_s_q_lite4_unity3d_1_1_not_null_constraint_violation_exception.html", null ],
      [ "PreparedSqlLiteInsertCommand", "class_s_q_lite4_unity3d_1_1_prepared_sql_lite_insert_command.html", null ],
      [ "PrimaryKeyAttribute", "class_s_q_lite4_unity3d_1_1_primary_key_attribute.html", null ],
      [ "SQLiteCommand", "class_s_q_lite4_unity3d_1_1_s_q_lite_command.html", "class_s_q_lite4_unity3d_1_1_s_q_lite_command" ],
      [ "SQLiteConnection", "class_s_q_lite4_unity3d_1_1_s_q_lite_connection.html", "class_s_q_lite4_unity3d_1_1_s_q_lite_connection" ],
      [ "SQLiteConnectionString", "class_s_q_lite4_unity3d_1_1_s_q_lite_connection_string.html", null ],
      [ "SQLiteException", "class_s_q_lite4_unity3d_1_1_s_q_lite_exception.html", null ],
      [ "TableAttribute", "class_s_q_lite4_unity3d_1_1_table_attribute.html", null ],
      [ "TableMapping", "class_s_q_lite4_unity3d_1_1_table_mapping.html", "class_s_q_lite4_unity3d_1_1_table_mapping" ],
      [ "TableQuery", "class_s_q_lite4_unity3d_1_1_table_query.html", null ],
      [ "UniqueAttribute", "class_s_q_lite4_unity3d_1_1_unique_attribute.html", null ]
    ] ],
    [ "AdvertisementManager", "class_advertisement_manager.html", null ],
    [ "Ball", "class_ball.html", "class_ball" ],
    [ "block", "classblock.html", null ],
    [ "DataManager", "class_data_manager.html", null ],
    [ "GameManager", "class_game_manager.html", "class_game_manager" ],
    [ "GameModeController", "class_game_mode_controller.html", "class_game_mode_controller" ],
    [ "OverlayManager", "class_overlay_manager.html", null ],
    [ "OverlaySetter", "class_overlay_setter.html", "class_overlay_setter" ],
    [ "SafeAreaSetter", "class_safe_area_setter.html", null ],
    [ "Scenemanager", "class_scenemanager.html", "class_scenemanager" ],
    [ "SerializableList", "class_serializable_list.html", null ],
    [ "ShopManager", "class_shop_manager.html", null ],
    [ "SkinAttributeManager", "class_skin_attribute_manager.html", null ],
    [ "Skins", "class_skins.html", "class_skins" ],
    [ "SkinSetter", "class_skin_setter.html", null ],
    [ "SkinsManager", "class_skins_manager.html", null ],
    [ "TrailController", "class_trail_controller.html", null ]
];