---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: Medoptics Market
  ConfigChange:
    PossibleAdd:
      Ticket:
        DynamicField_Market:
        - '120'
        - 'Medoptics'
  ConfigMatch:
    Properties:
      User:
        UserCustomerID:
        - '[RegExp]^([1-1][2-2][0-9])$'
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: Unrelated Markets will be hidden.
  ID: 8
  Name: AAM Agent Medoptics
  StopAfterMatch: 0
  ValidID: 1
