---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: ''
  ConfigChange:
    PossibleAdd:
      Process:
      - '[RegExp]^.'
  ConfigMatch:
    Properties:
      User:
        Group_rw:
        - 'admin'
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: Unrelated processes will be hidden.
  ID: 7
  Name: AAP Admin Processes
  StopAfterMatch: 0
  ValidID: 1
