---
- ChangeBy: admin
  ChangeTime: 2018-06-28 20:47:59
  Comment: ''
  ConfigChange:
    Possible: {}
    PossibleAdd:
      Process:
      - Process-3e624fc75145d4696569f0d54c07cb67
      - Process-f728bbb6b15ea140b77319ee7962c6db
      - Process-dd22d29815efb5c33315c7433049ebdc
  ConfigMatch:
    Properties:
      CustomerUser:
        UserCustomerID:
        - '110'
  CreateBy: root@localhost
  CreateTime: 2018-06-27 22:56:51
  Description: Unrelated processes will be hidden.
  ID: '24'
  Name: AAP Digicam Customer Processes
  StopAfterMatch: 0
  ValidID: '1'
