# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSeleniumtest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_seleniumtest(self):
    self.driver.get("https://www.campus.fh-aachen.de/campus/all/groups.asp?tguid=0x6D4B18790AAA451FAAEC4E1140F42595&lang=de")
    self.driver.set_window_size(859, 913)
    self.driver.find_element(By.LINK_TEXT, "Suchen").click()
    self.driver.find_element(By.ID, "find").click()
    self.driver.find_element(By.ID, "find").send_keys("Kryptologie")
    self.driver.find_element(By.ID, "searchobject").click()
    dropdown = self.driver.find_element(By.ID, "searchobject")
    dropdown.find_element(By.XPATH, "//option[. = 'Modul']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#searchobject > option:nth-child(2)").click()
    self.driver.find_element(By.ID, "campusSearchButton").click()
    self.driver.find_element(By.LINK_TEXT, "Suchen").click()
    self.driver.find_element(By.ID, "find").click()
    self.driver.find_element(By.ID, "find").send_keys("Hoever, Georg")
    self.driver.find_element(By.ID, "searchobject").click()
    dropdown = self.driver.find_element(By.ID, "searchobject")
    dropdown.find_element(By.XPATH, "//option[. = 'Person (Nachname und Vorname)']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#searchobject > option:nth-child(3)").click()
    self.driver.find_element(By.ID, "campusSearchButton").click()
    self.driver.find_element(By.LINK_TEXT, "Suchen").click()
    time.sleep(15)
  
