---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: Market EUROPE
  ConfigChange:
    PossibleAdd:
      Ticket:
        DynamicField_Market:
        - 'DACH'
        - 'BENELUX'
        - 'EUROPE'
  ConfigMatch:
    Properties:
      User:
        Role:
        - 'Agent::1st-Lvl::EUROPE'
        - 'Agent::2nd-Lvl::EUROPE'
        - 'Agent::3rd-Lvl::EUROPE'
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: Unrelated Markets will be hidden.
  ID: 9
  Name: AAM Agent EUROPE
  StopAfterMatch: 0
  ValidID: 1
