---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: Market DACH
  ConfigChange:
    PossibleAdd:
      Ticket:
        DynamicField_Market:
        - '102'
        - 'DACH'
  ConfigMatch:
    Properties:
      CustomerUser:
        UserCustomerID:
        - 'DACH'
        - '102'
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: Unrelated Markets will be hidden.
  ID: 8
  Name: AAM Customer DACH 
  StopAfterMatch: 0
  ValidID: 1
