---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: Market NAM
  ConfigChange:
    PossibleAdd:
      Ticket:
        DynamicField_Market:
        - '104'
        - 'NAM'
  ConfigMatch:
    Properties:
      CustomerUser:
        UserCustomerID:
        - 'NAM'
        - '104'
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: Unrelated Markets will be hidden.
  ID: 8
  Name: AAM Customer NAM 
  StopAfterMatch: 0
  ValidID: 1
