---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: Market LATAM
  ConfigChange:
    PossibleAdd:
      Ticket:
        DynamicField_Market:
        - '105'
        - 'LATAM'
  ConfigMatch:
    Properties:
      CustomerUser:
        UserCustomerID:
        - 'LATAM'
        - '105'
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: Unrelated Markets will be hidden.
  ID: 8
  Name: AAM Customer LATAM 
  StopAfterMatch: 0
  ValidID: 1
