---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: Market DACH
  ConfigChange:
    PossibleAdd:
      Ticket:
        DynamicField_Market:
        - '102'
        - 'DACH'
  ConfigMatch:
    Properties:
      User:
        Role:
        - 'Agent::1st-Lvl::DACH'
        - 'Agent::2nd-Lvl::DACH'
        - 'Agent::3rd-Lvl::DACH'
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: Unrelated Markets will be hidden.
  ID: 8
  Name: AAM Agent DACH 
  StopAfterMatch: 0
  ValidID: 1
