---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: Market BENELUX
  ConfigChange:
    PossibleAdd:
      Ticket:
        DynamicField_Market:
        - '103'
        - 'BENELUX'
  ConfigMatch:
    Properties:
      User:
        Role:
        - 'Agent::1st-Lvl::BENELUX'
        - 'Agent::2nd-Lvl::BENELUX'
        - 'Agent::3rd-Lvl::BENELUX'
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: Unrelated Markets will be hidden.
  ID: 9
  Name: AAM Agent BENELUX
  StopAfterMatch: 0
  ValidID: 1
