---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: Market BENELUX
  ConfigChange:
    PossibleAdd:
      Ticket:
        DynamicField_Market:
        - '103'
        - 'BENELUX'
  ConfigMatch:
    Properties:
      CustomerUser:
        UserCustomerID:
        - 'BENELUX'
        - '103'
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: Unrelated Markets will be hidden.
  ID: 8
  Name: AAM Customer BENELUX 
  StopAfterMatch: 0
  ValidID: 1
