---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: Market WORLDWIDE
  ConfigChange:
    PossibleAdd:
      Ticket:
        DynamicField_Market:
        - 'DACH'
        - 'BENELUX'
        - 'EUROPE'
        - 'NAM'
        - 'LATAM'
        - 'AMERICA'
        - 'WORLDWIDE'
  ConfigMatch:
    Properties:
      User:
        Role:
        - 'Agent::1st-Lvl::WORLDWIDE'
        - 'Agent::2nd-Lvl::WORLDWIDE'
        - 'Agent::3rd-Lvl::WORLDWIDE'
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: Unrelated Markets will be hidden.
  ID: 9
  Name: AAM Agent WORLDWIDE
  StopAfterMatch: 0
  ValidID: 1
