---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: Market EUROPE
  ConfigChange:
    PossibleAdd:
      Ticket:
        DynamicField_Market:
        - '106'
        - 'EUROPE'
  ConfigMatch:
    Properties:
      CustomerUser:
        UserCustomerID:
        - 'EUROPE'
        - '106'
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: Unrelated Markets will be hidden.
  ID: 8
  Name: AAM Customer EUROPE 
  StopAfterMatch: 0
  ValidID: 1
