FROM ubuntu:18.04
LABEL maintainer="Andreas Classen <a.classen@fh-aachen.de>"
# Install Java 8 ...
RUN     apt update &&         apt-get -y install software-properties-common &&         apt-get install -y openjdk-8-jdk &&         apt-get install -y wget
CMD /bin/bash
