FROM myjava8-image
LABEL maintainer="Andreas Classen <a.classen@fh-aachen.de>"
WORKDIR /root
# Install Elasticsearch ...
RUN apt-get install -y curl iputils-ping vim nano && wget --quiet https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.13.deb && dpkg-divert --rename /usr/lib/sysctl.d/elasticsearch.conf && dpkg -i elasticsearch-*.deb
# Install filebeat ...
RUN wget --quiet https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.8.13-amd64.deb && dpkg -i filebeat*.deb
# Since Elastic 7.1 part of the default distribution ...
# RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch ingest-user-agent
# RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch ingest-geoip
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
COPY es_start.sh ./es_start.sh
RUN chmod a+x ./es_start.sh
# 9200: HTTP
# 9300: transport
EXPOSE 9200
EXPOSE 9300
ENTRYPOINT ["/root/es_start.sh"]
