---
Activities:
  Activity-169261b8d7fba5c1c76ac8a47d28532a:
    ActivityDialogs:
    - ActivityDialog-fd2204c0d3197c1af116ae4873f08f6f
    - ActivityDialog-1d379346f36166a17220f346d7c6f189
    ChangeTime: 2018-06-27 22:57:02
    Config:
      ActivityDialog:
        '1': ActivityDialog-fd2204c0d3197c1af116ae4873f08f6f
        '2': ActivityDialog-1d379346f36166a17220f346d7c6f189
    CreateTime: 2018-06-27 22:57:02
    EntityID: Activity-169261b8d7fba5c1c76ac8a47d28532a
    ID: '4'
    Name: ':: Provide Solution (1st-Lvl)'
  Activity-61b2b9d8c601c7e4f3cc6faa53a5233c:
    ActivityDialogs:
    - ActivityDialog-fd2204c0d3197c1af116ae4873f08f6f
    - ActivityDialog-1d379346f36166a17220f346d7c6f189
    ChangeTime: 2018-06-27 22:57:02
    Config:
      ActivityDialog:
        '1': ActivityDialog-fd2204c0d3197c1af116ae4873f08f6f
        '2': ActivityDialog-1d379346f36166a17220f346d7c6f189
    CreateTime: 2018-06-27 22:57:02
    EntityID: Activity-61b2b9d8c601c7e4f3cc6faa53a5233c
    ID: '6'
    Name: ':: Provide Solution (2nd-Lvl)'
  Activity-7f9becb231d6423ff413fde0850fe400:
    ActivityDialogs: []
    ChangeTime: 2018-06-27 22:57:02
    Config: {}
    CreateTime: 2018-06-27 22:57:02
    EntityID: Activity-7f9becb231d6423ff413fde0850fe400
    ID: '2'
    Name: Completed
  Activity-b0b36e2a264e07526abb2aec5e5de254:
    ActivityDialogs:
    - ActivityDialog-fd2204c0d3197c1af116ae4873f08f6f
    ChangeTime: 2018-06-27 22:57:02
    Config:
      ActivityDialog:
        '1': ActivityDialog-fd2204c0d3197c1af116ae4873f08f6f
    CreateTime: 2018-06-27 22:57:02
    EntityID: Activity-b0b36e2a264e07526abb2aec5e5de254
    ID: '7'
    Name: ':: Provide Solution (3rd-Lvl)'
  Activity-f68e0ef84a4c445df2bb1c8480904540:
    ActivityDialogs:
    - ActivityDialog-13b13f405accaa0e61b9022fbb8cf68d
    ChangeTime: 2018-06-27 22:57:07
    Config:
      ActivityDialog:
        '1': ActivityDialog-13b13f405accaa0e61b9022fbb8cf68d
    CreateTime: 2018-06-27 22:57:07
    EntityID: Activity-f68e0ef84a4c445df2bb1c8480904540
    ID: '16'
    Name: 'Digicam :: Request for Information'
ActivityDialogs:
  ActivityDialog-13b13f405accaa0e61b9022fbb8cf68d:
    ChangeTime: 2018-06-28 20:49:07
    Config:
      DescriptionLong: ''
      DescriptionShort: Please describe your problem.
      FieldOrder:
      - DynamicField_Market
      - DynamicField_DIGIproduct
      - DynamicField_DIGImodelnr
      - Article
      Fields:
        Article:
          Config:
            CommunicationChannel: Internal
            IsVisibleForCustomer: '0'
          DefaultValue: ''
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '2'
        DynamicField_DIGImodelnr:
          DefaultValue: ''
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '1'
        DynamicField_DIGIproduct:
          DefaultValue: ''
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '1'
        DynamicField_Market:
          DefaultValue: Digicam
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '0'
      Interface:
      - AgentInterface
      - CustomerInterface
      Permission: ''
      RequiredLock: 0
      SubmitAdviceText: ''
      SubmitButtonText: ''
    CreateTime: 2018-06-27 22:57:07
    EntityID: ActivityDialog-13b13f405accaa0e61b9022fbb8cf68d
    ID: '14'
    Name: 'Digicam :: Request for Information'
  ActivityDialog-1d379346f36166a17220f346d7c6f189:
    ChangeTime: 2018-06-27 22:57:07
    Config:
      DescriptionLong: ''
      DescriptionShort: Escalate the ticket to the next level.
      FieldOrder:
      - DynamicField_Description
      - DynamicField_Escalate
      Fields:
        DynamicField_Description:
          DefaultValue: ''
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '1'
        DynamicField_Escalate:
          DefaultValue: '1'
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '0'
      Interface:
      - AgentInterface
      Permission: rw
      RequiredLock: '0'
      SubmitAdviceText: ''
      SubmitButtonText: level up
    CreateTime: 2018-06-27 22:57:02
    EntityID: ActivityDialog-1d379346f36166a17220f346d7c6f189
    ID: '3'
    Name: ':: Escalate'
  ActivityDialog-fd2204c0d3197c1af116ae4873f08f6f:
    ChangeTime: 2018-06-27 22:57:07
    Config:
      DescriptionLong: ''
      DescriptionShort: Please describe your solution.
      FieldOrder:
      - State
      - DynamicField_Description
      - DynamicField_Solution
      Fields:
        DynamicField_Description:
          DefaultValue: ''
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '1'
        DynamicField_Solution:
          DefaultValue: '1'
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '0'
        State:
          DefaultValue: ''
          DescriptionLong: ''
          DescriptionShort: completion status
          Display: '2'
      Interface:
      - AgentInterface
      Permission: ''
      RequiredLock: '0'
      SubmitAdviceText: ''
      SubmitButtonText: ''
    CreateTime: 2018-06-27 22:57:02
    EntityID: ActivityDialog-fd2204c0d3197c1af116ae4873f08f6f
    ID: '5'
    Name: ':: Provide Solution'
Process:
  Activities:
  - Activity-169261b8d7fba5c1c76ac8a47d28532a
  - Activity-61b2b9d8c601c7e4f3cc6faa53a5233c
  - Activity-7f9becb231d6423ff413fde0850fe400
  - Activity-b0b36e2a264e07526abb2aec5e5de254
  - Activity-f68e0ef84a4c445df2bb1c8480904540
  ChangeTime: 2018-06-27 22:57:07
  Config:
    Description: All request without reference to a specific process.
    Path:
      Activity-169261b8d7fba5c1c76ac8a47d28532a:
        Transition-b2f2c80df7ed1c01ba0e5185c846cb31:
          ActivityEntityID: Activity-61b2b9d8c601c7e4f3cc6faa53a5233c
          TransitionAction:
          - TransitionAction-95ab9b458a9b8ba8e6067e706f2b282a
        Transition-efce41201952c0c0b5778d1ab13ea1f1:
          ActivityEntityID: Activity-7f9becb231d6423ff413fde0850fe400
          TransitionAction: []
      Activity-61b2b9d8c601c7e4f3cc6faa53a5233c:
        Transition-b2f2c80df7ed1c01ba0e5185c846cb31:
          ActivityEntityID: Activity-b0b36e2a264e07526abb2aec5e5de254
          TransitionAction:
          - TransitionAction-95ab9b458a9b8ba8e6067e706f2b282a
        Transition-efce41201952c0c0b5778d1ab13ea1f1:
          ActivityEntityID: Activity-7f9becb231d6423ff413fde0850fe400
      Activity-7f9becb231d6423ff413fde0850fe400: {}
      Activity-b0b36e2a264e07526abb2aec5e5de254:
        Transition-efce41201952c0c0b5778d1ab13ea1f1:
          ActivityEntityID: Activity-7f9becb231d6423ff413fde0850fe400
      Activity-f68e0ef84a4c445df2bb1c8480904540:
        Transition-2b1089ad532ca8712045640ce30749ec:
          ActivityEntityID: Activity-169261b8d7fba5c1c76ac8a47d28532a
          TransitionAction:
          - TransitionAction-3ec358befc37c68eb0dd463d6382df47
    StartActivity: Activity-f68e0ef84a4c445df2bb1c8480904540
    StartActivityDialog: ActivityDialog-13b13f405accaa0e61b9022fbb8cf68d
  CreateTime: 2018-06-27 22:57:07
  EntityID: Process-dd22d29815efb5c33315c7433049ebdc
  ID: '9'
  Layout:
    Activity-169261b8d7fba5c1c76ac8a47d28532a:
      left: '546'
      top: '12'
    Activity-61b2b9d8c601c7e4f3cc6faa53a5233c:
      left: '547'
      top: '151'
    Activity-7f9becb231d6423ff413fde0850fe400:
      left: '962'
      top: '155.916687011719'
    Activity-b0b36e2a264e07526abb2aec5e5de254:
      left: '549'
      top: '307'
    Activity-f68e0ef84a4c445df2bb1c8480904540:
      left: '234'
      top: '97.9166870117188'
  Name: 'Digicam :: Request for Information'
  State: Active
  StateEntityID: S1
  TransitionActions:
  - TransitionAction-95ab9b458a9b8ba8e6067e706f2b282a
  - TransitionAction-95ab9b458a9b8ba8e6067e706f2b282a
  - TransitionAction-3ec358befc37c68eb0dd463d6382df47
  Transitions:
  - Transition-b2f2c80df7ed1c01ba0e5185c846cb31
  - Transition-efce41201952c0c0b5778d1ab13ea1f1
  - Transition-b2f2c80df7ed1c01ba0e5185c846cb31
  - Transition-efce41201952c0c0b5778d1ab13ea1f1
  - Transition-efce41201952c0c0b5778d1ab13ea1f1
  - Transition-2b1089ad532ca8712045640ce30749ec
TransitionActions:
  TransitionAction-3ec358befc37c68eb0dd463d6382df47:
    ChangeTime: 2018-06-27 22:57:07
    Config:
      Config:
        Queue: <OTRS_TICKET_DynamicField_Market_Value>
      Module: Kernel::System::ProcessManagement::TransitionAction::TicketQueueSet
    CreateTime: 2018-06-27 22:57:07
    EntityID: TransitionAction-3ec358befc37c68eb0dd463d6382df47
    ID: '3'
    Name: Queue::Digicam::<Market>
  TransitionAction-95ab9b458a9b8ba8e6067e706f2b282a:
    ChangeTime: 2018-06-27 22:57:07
    Config:
      Config:
        Escalate: '0'
      Module: Kernel::System::ProcessManagement::TransitionAction::DynamicFieldSet
    CreateTime: 2018-06-27 22:57:07
    EntityID: TransitionAction-95ab9b458a9b8ba8e6067e706f2b282a
    ID: '4'
    Name: Escalation::Reset
Transitions:
  Transition-2b1089ad532ca8712045640ce30749ec:
    ChangeTime: 2018-06-27 22:57:02
    Config:
      Condition:
        '1':
          Fields:
            DynamicField_ProcessManagementProcessID:
              Match: ^.
              Type: Regexp
          Type: and
      ConditionLinking: and
    CreateTime: 2018-06-27 22:57:02
    EntityID: Transition-2b1089ad532ca8712045640ce30749ec
    ID: '1'
    Name: Always Move
  Transition-b2f2c80df7ed1c01ba0e5185c846cb31:
    ChangeTime: 2018-06-27 22:57:02
    Config:
      Condition:
        '1':
          Fields:
            DynamicField_Escalate:
              Match: '1'
              Type: Regexp
          Type: and
      ConditionLinking: and
    CreateTime: 2018-06-27 22:57:02
    EntityID: Transition-b2f2c80df7ed1c01ba0e5185c846cb31
    ID: '3'
    Name: Escalation
  Transition-efce41201952c0c0b5778d1ab13ea1f1:
    ChangeTime: 2018-06-27 22:57:02
    Config:
      Condition:
        '1':
          Fields:
            DynamicField_Solution:
              Match: '1'
              Type: Regexp
          Type: and
      ConditionLinking: and
    CreateTime: 2018-06-27 22:57:02
    EntityID: Transition-efce41201952c0c0b5778d1ab13ea1f1
    ID: '2'
    Name: Solution
