---
Activities:
  Activity-5584d84b10ca0f779fce263789f59196:
    ActivityDialogs:
    - ActivityDialog-2c231bf683304ad0d6825ab962bd3d71
    - ActivityDialog-ae0510244f5606099f06c184380b9b40
    ChangeTime: 2018-03-26 19:15:51
    Config:
      ActivityDialog:
        '1': ActivityDialog-2c231bf683304ad0d6825ab962bd3d71
        '2': ActivityDialog-ae0510244f5606099f06c184380b9b40
    CreateTime: 2018-03-26 19:15:51
    EntityID: Activity-5584d84b10ca0f779fce263789f59196
    ID: '18'
    Name: 'Digicam :: Accounting'
  Activity-60ea13d38683f81b0afe1e26acc9f10c:
    ActivityDialogs:
    - ActivityDialog-10eb27c46a100249f964313da4ff7c6d
    ChangeTime: 2018-03-26 19:15:51
    Config:
      ActivityDialog:
        '1': ActivityDialog-10eb27c46a100249f964313da4ff7c6d
    CreateTime: 2018-03-26 19:15:51
    EntityID: Activity-60ea13d38683f81b0afe1e26acc9f10c
    ID: '19'
    Name: 'Digicam :: Hardware Order'
  Activity-7f9becb231d6423ff413fde0850fe400:
    ActivityDialogs: []
    ChangeTime: 2018-03-26 19:09:43
    Config: {}
    CreateTime: 2018-03-26 19:09:43
    EntityID: Activity-7f9becb231d6423ff413fde0850fe400
    ID: '11'
    Name: Completed
  Activity-c56063b1265f5e014a1c235e3db3464c:
    ActivityDialogs:
    - ActivityDialog-e6b2eb119300123794709a54a44b7d28
    - ActivityDialog-33428d1d211895a5de7408495e7dd7df
    - ActivityDialog-2ffa0f30cfd77beaa37508cbdeb926ee
    ChangeTime: 2018-03-26 19:15:51
    Config:
      ActivityDialog:
        '1': ActivityDialog-e6b2eb119300123794709a54a44b7d28
        '2': ActivityDialog-33428d1d211895a5de7408495e7dd7df
        '3': ActivityDialog-2ffa0f30cfd77beaa37508cbdeb926ee
    CreateTime: 2018-03-26 19:15:51
    EntityID: Activity-c56063b1265f5e014a1c235e3db3464c
    ID: '20'
    Name: 'Digicam :: Delivery'
  Activity-cb04bc78166babd2c2a28cb10413cf3f:
    ActivityDialogs:
    - ActivityDialog-7f0197b4e79885c587531d591f767377
    ChangeTime: 2018-03-26 19:15:51
    Config:
      ActivityDialog:
        '1': ActivityDialog-7f0197b4e79885c587531d591f767377
    CreateTime: 2018-03-26 19:15:51
    EntityID: Activity-cb04bc78166babd2c2a28cb10413cf3f
    ID: '21'
    Name: 'Digicam :: Order Desk'
ActivityDialogs:
  ActivityDialog-10eb27c46a100249f964313da4ff7c6d:
    ChangeTime: 2018-04-08 23:42:43
    Config:
      DescriptionLong: ''
      DescriptionShort: Please fill in the purchase order from.
      FieldOrder:
      - DynamicField_Market
      - DynamicField_DIGIproduct
      - DynamicField_DIGIdeliveryAddress
      Fields:
        DynamicField_DIGIdeliveryAddress:
          DefaultValue: ''
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '2'
        DynamicField_DIGIproduct:
          DefaultValue: ''
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '2'
        DynamicField_Market:
          DefaultValue: Digicam
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '0'
      Interface:
      - AgentInterface
      - CustomerInterface
      Permission: ''
      RequiredLock: 0
      SubmitAdviceText: ''
      SubmitButtonText: ''
    CreateTime: 2018-03-26 19:15:51
    EntityID: ActivityDialog-10eb27c46a100249f964313da4ff7c6d
    ID: '15'
    Name: 'Digicam :: Hardware Order'
  ActivityDialog-2c231bf683304ad0d6825ab962bd3d71:
    ChangeTime: 2018-03-26 19:15:51
    Config:
      DescriptionLong: ''
      DescriptionShort: Please process the order.
      FieldOrder:
      - Article
      Fields:
        Article:
          Config:
            CommunicationChannel: Internal
            IsVisibleForCustomer: '0'
            TimeUnits: '0'
          DefaultValue: ''
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '1'
      Interface:
      - AgentInterface
      Permission: ''
      RequiredLock: 0
      SubmitAdviceText: ''
      SubmitButtonText: ''
    CreateTime: 2018-03-26 19:15:51
    EntityID: ActivityDialog-2c231bf683304ad0d6825ab962bd3d71
    ID: '16'
    Name: 'Digicam :: Consumer Accounting'
  ActivityDialog-2ffa0f30cfd77beaa37508cbdeb926ee:
    ChangeTime: 2018-03-26 19:15:51
    Config:
      DescriptionLong: ''
      DescriptionShort: Please fill in the fields.
      FieldOrder:
      - DynamicField_DIGIdeliveryTime
      - DynamicField_DIGIdeliveryAddress
      Fields:
        DynamicField_DIGIdeliveryAddress:
          DefaultValue: ''
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '1'
        DynamicField_DIGIdeliveryTime:
          DefaultValue: ''
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '2'
      Interface:
      - AgentInterface
      Permission: ''
      RequiredLock: 0
      SubmitAdviceText: ''
      SubmitButtonText: ''
    CreateTime: 2018-03-26 19:15:51
    EntityID: ActivityDialog-2ffa0f30cfd77beaa37508cbdeb926ee
    ID: '17'
    Name: 'Digicam :: Delivery :: Sent'
  ActivityDialog-33428d1d211895a5de7408495e7dd7df:
    ChangeTime: 2018-03-26 19:15:51
    Config:
      DescriptionLong: ''
      DescriptionShort: Please fill in the fields.
      FieldOrder: []
      Fields: {}
      Interface:
      - AgentInterface
      Permission: ''
      RequiredLock: 0
      SubmitAdviceText: ''
      SubmitButtonText: ''
    CreateTime: 2018-03-26 19:15:51
    EntityID: ActivityDialog-33428d1d211895a5de7408495e7dd7df
    ID: '18'
    Name: 'Digicam :: Delivery :: Packed'
  ActivityDialog-7f0197b4e79885c587531d591f767377:
    ChangeTime: 2018-03-26 19:15:51
    Config:
      DescriptionLong: ''
      DescriptionShort: Please review the customer provided data.
      FieldOrder:
      - DynamicField_DIGIorderApproval
      - DynamicField_DIGIorderNumber
      - DynamicField_DIGIinvoiceNumber
      Fields:
        DynamicField_DIGIinvoiceNumber:
          DefaultValue: ''
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '2'
        DynamicField_DIGIorderApproval:
          DefaultValue: ''
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '2'
        DynamicField_DIGIorderNumber:
          DefaultValue: ''
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '2'
      Interface:
      - AgentInterface
      Permission: ''
      RequiredLock: 0
      SubmitAdviceText: ''
      SubmitButtonText: ''
    CreateTime: 2018-03-26 19:15:51
    EntityID: ActivityDialog-7f0197b4e79885c587531d591f767377
    ID: '19'
    Name: 'Digicam :: Order Desk'
  ActivityDialog-ae0510244f5606099f06c184380b9b40:
    ChangeTime: 2018-03-26 19:15:51
    Config:
      DescriptionLong: ''
      DescriptionShort: Please process the order.
      FieldOrder: []
      Fields: {}
      Interface:
      - AgentInterface
      Permission: ''
      RequiredLock: 0
      SubmitAdviceText: ''
      SubmitButtonText: ''
    CreateTime: 2018-03-26 19:15:51
    EntityID: ActivityDialog-ae0510244f5606099f06c184380b9b40
    ID: '20'
    Name: 'Digicam :: Enterprise Accounting'
  ActivityDialog-e6b2eb119300123794709a54a44b7d28:
    ChangeTime: 2018-03-26 19:15:51
    Config:
      DescriptionLong: ''
      DescriptionShort: Please fill in the fields.
      FieldOrder:
      - Priority
      - DynamicField_DIGIdeliveryDuration
      Fields:
        DynamicField_DIGIdeliveryDuration:
          DefaultValue: ''
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '2'
        Priority:
          DefaultValue: ''
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '2'
      Interface:
      - AgentInterface
      Permission: ''
      RequiredLock: 0
      SubmitAdviceText: ''
      SubmitButtonText: ''
    CreateTime: 2018-03-26 19:15:51
    EntityID: ActivityDialog-e6b2eb119300123794709a54a44b7d28
    ID: '21'
    Name: 'Digicam :: Delivery :: In Progress'
Process:
  Activities:
  - Activity-5584d84b10ca0f779fce263789f59196
  - Activity-60ea13d38683f81b0afe1e26acc9f10c
  - Activity-7f9becb231d6423ff413fde0850fe400
  - Activity-c56063b1265f5e014a1c235e3db3464c
  - Activity-cb04bc78166babd2c2a28cb10413cf3f
  ChangeTime: 2018-03-26 19:15:51
  Config:
    Description: Request new Hardware
    Path:
      Activity-5584d84b10ca0f779fce263789f59196:
        Transition-9c2e7a0bc6fb94d26e310eb1817b478c:
          ActivityEntityID: Activity-7f9becb231d6423ff413fde0850fe400
          TransitionAction:
          - TransitionAction-680a39e47dd8327943de20dc8498e34a
        Transition-b94dd4d420b01214eabc4a1224cd3828:
          ActivityEntityID: Activity-c56063b1265f5e014a1c235e3db3464c
          TransitionAction:
          - TransitionAction-3ec358befc37c68eb0dd463d6382df47
      Activity-60ea13d38683f81b0afe1e26acc9f10c:
        Transition-2b1089ad532ca8712045640ce30749ec:
          ActivityEntityID: Activity-cb04bc78166babd2c2a28cb10413cf3f
          TransitionAction:
          - TransitionAction-3ec358befc37c68eb0dd463d6382df47
          - TransitionAction-7b3028f075c6e8c6e52efed183c1470d
      Activity-7f9becb231d6423ff413fde0850fe400: {}
      Activity-c56063b1265f5e014a1c235e3db3464c:
        Transition-bbe2363e064615326c8683d97cb10da4:
          ActivityEntityID: Activity-7f9becb231d6423ff413fde0850fe400
          TransitionAction:
          - TransitionAction-6eae0ba8fd49ce0ef14f06e4c7ec1193
      Activity-cb04bc78166babd2c2a28cb10413cf3f:
        Transition-07803975a9d21552a1875829e60709b4:
          ActivityEntityID: Activity-5584d84b10ca0f779fce263789f59196
          TransitionAction:
          - TransitionAction-7b3028f075c6e8c6e52efed183c1470d
        Transition-24de3342986ebd964058f8bd9dd2bf35:
          ActivityEntityID: Activity-5584d84b10ca0f779fce263789f59196
          TransitionAction:
          - TransitionAction-a0bc31792ae23f62df1ad85ffb69434f
        Transition-9c2e7a0bc6fb94d26e310eb1817b478c:
          ActivityEntityID: Activity-7f9becb231d6423ff413fde0850fe400
          TransitionAction:
          - TransitionAction-680a39e47dd8327943de20dc8498e34a
    StartActivity: Activity-60ea13d38683f81b0afe1e26acc9f10c
    StartActivityDialog: ActivityDialog-10eb27c46a100249f964313da4ff7c6d
  CreateTime: 2018-03-26 19:15:51
  EntityID: Process-3e624fc75145d4696569f0d54c07cb67
  ID: '13'
  Layout:
    Activity-5584d84b10ca0f779fce263789f59196:
      left: '591'
      top: '20'
    Activity-60ea13d38683f81b0afe1e26acc9f10c:
      left: '52'
      top: '78'
    Activity-7f9becb231d6423ff413fde0850fe400:
      left: '843'
      top: '325'
    Activity-c56063b1265f5e014a1c235e3db3464c:
      left: '884'
      top: '165'
    Activity-cb04bc78166babd2c2a28cb10413cf3f:
      left: '218'
      top: '182'
  Name: 'Digicam :: Hardware Order'
  State: Active
  StateEntityID: S1
  TransitionActions:
  - TransitionAction-680a39e47dd8327943de20dc8498e34a
  - TransitionAction-3ec358befc37c68eb0dd463d6382df47
  - TransitionAction-3ec358befc37c68eb0dd463d6382df47
  - TransitionAction-7b3028f075c6e8c6e52efed183c1470d
  - TransitionAction-6eae0ba8fd49ce0ef14f06e4c7ec1193
  - TransitionAction-7b3028f075c6e8c6e52efed183c1470d
  - TransitionAction-a0bc31792ae23f62df1ad85ffb69434f
  - TransitionAction-680a39e47dd8327943de20dc8498e34a
  Transitions:
  - Transition-9c2e7a0bc6fb94d26e310eb1817b478c
  - Transition-b94dd4d420b01214eabc4a1224cd3828
  - Transition-2b1089ad532ca8712045640ce30749ec
  - Transition-bbe2363e064615326c8683d97cb10da4
  - Transition-07803975a9d21552a1875829e60709b4
  - Transition-24de3342986ebd964058f8bd9dd2bf35
  - Transition-9c2e7a0bc6fb94d26e310eb1817b478c
TransitionActions:
  TransitionAction-3ec358befc37c68eb0dd463d6382df47:
    ChangeTime: 2018-03-26 19:12:11
    Config:
      Config:
        Queue: <OTRS_TICKET_DynamicField_Market_Value>
      Module: Kernel::System::ProcessManagement::TransitionAction::TicketQueueSet
    CreateTime: 2018-03-26 19:12:11
    EntityID: TransitionAction-3ec358befc37c68eb0dd463d6382df47
    ID: '1'
    Name: Queue::Digicam::<Market>
  TransitionAction-680a39e47dd8327943de20dc8498e34a:
    ChangeTime: 2018-03-26 19:15:51
    Config:
      Config:
        State: close unsuccessful
      Module: Kernel::System::ProcessManagement::TransitionAction::TicketStateSet
    CreateTime: 2018-03-26 19:15:51
    EntityID: TransitionAction-680a39e47dd8327943de20dc8498e34a
    ID: '3'
    Name: State::Close unsuccessful
  TransitionAction-6eae0ba8fd49ce0ef14f06e4c7ec1193:
    ChangeTime: 2018-03-26 19:15:51
    Config:
      Config:
        State: close successful
      Module: Kernel::System::ProcessManagement::TransitionAction::TicketStateSet
    CreateTime: 2018-03-26 19:15:51
    EntityID: TransitionAction-6eae0ba8fd49ce0ef14f06e4c7ec1193
    ID: '4'
    Name: State::Close successful
  TransitionAction-7b3028f075c6e8c6e52efed183c1470d:
    ChangeTime: 2018-03-26 19:15:51
    Config:
      Config:
        Queue: Digicam EUROPE
      Module: Kernel::System::ProcessManagement::TransitionAction::TicketQueueSet
    CreateTime: 2018-03-26 19:15:51
    EntityID: TransitionAction-7b3028f075c6e8c6e52efed183c1470d
    ID: '5'
    Name: Queue::Digicam::EUROPE
  TransitionAction-a0bc31792ae23f62df1ad85ffb69434f:
    ChangeTime: 2018-03-26 19:15:51
    Config:
      Config:
        Queue: Digicam AMERICA
      Module: Kernel::System::ProcessManagement::TransitionAction::TicketQueueSet
    CreateTime: 2018-03-26 19:15:51
    EntityID: TransitionAction-a0bc31792ae23f62df1ad85ffb69434f
    ID: '6'
    Name: Queue::Digicam::AMERICA
Transitions:
  Transition-07803975a9d21552a1875829e60709b4:
    ChangeTime: 2018-03-26 19:15:51
    Config:
      Condition:
        '1':
          Fields:
            DynamicField_DIGIrequestApproval:
              Match: '1'
              Type: Module
          Type: and
        '2':
          Fields:
            DynamicField_Market:
              Match: EUROPE
              Type: Regexp
          Type: and
      ConditionLinking: and
    CreateTime: 2018-03-26 19:15:51
    EntityID: Transition-07803975a9d21552a1875829e60709b4
    ID: '4'
    Name: 'Digicam :: Order Request :: Europe'
  Transition-24de3342986ebd964058f8bd9dd2bf35:
    ChangeTime: 2018-03-26 19:15:51
    Config:
      Condition:
        '1':
          Fields:
            DynamicField_DIGIrequestApproval:
              Match: '1'
              Type: String
          Type: and
        '2':
          Fields:
            DynamicField_Market:
              Match: AMERICA
              Type: Regexp
          Type: and
      ConditionLinking: and
    CreateTime: 2018-03-26 19:15:51
    EntityID: Transition-24de3342986ebd964058f8bd9dd2bf35
    ID: '5'
    Name: 'Digicam :: Order Request :: America'
  Transition-2b1089ad532ca8712045640ce30749ec:
    ChangeTime: 2018-03-26 19:09:43
    Config:
      Condition:
        '1':
          Fields:
            DynamicField_ProcessManagementProcessID:
              Match: ^.
              Type: Regexp
          Type: and
      ConditionLinking: and
    CreateTime: 2018-03-26 19:09:43
    EntityID: Transition-2b1089ad532ca8712045640ce30749ec
    ID: '1'
    Name: Always Move
  Transition-9c2e7a0bc6fb94d26e310eb1817b478c:
    ChangeTime: 2018-03-26 19:15:51
    Config:
      Condition:
        '1':
          Fields:
            DynamicField_DIGIorderApproval:
              Match: '2'
              Type: String
            DynamicField_DIGIrequestApproval:
              Match: '2'
              Type: Regexp
          Type: or
      ConditionLinking: and
    CreateTime: 2018-03-26 19:15:51
    EntityID: Transition-9c2e7a0bc6fb94d26e310eb1817b478c
    ID: '6'
    Name: 'Digicam :: Order Request :: Declined'
  Transition-b94dd4d420b01214eabc4a1224cd3828:
    ChangeTime: 2018-03-26 19:15:51
    Config:
      Condition:
        '1':
          Fields:
            DynamicField_DIGIorderApproval:
              Match: '1'
              Type: Regexp
          Type: and
      ConditionLinking: and
    CreateTime: 2018-03-26 19:15:51
    EntityID: Transition-b94dd4d420b01214eabc4a1224cd3828
    ID: '7'
    Name: 'Digicam :: Order Request :: Payed'
  Transition-bbe2363e064615326c8683d97cb10da4:
    ChangeTime: 2018-03-26 19:15:51
    Config:
      Condition:
        '1':
          Fields:
            DynamicField_DIGIorderSent:
              Match: '1'
              Type: String
          Type: and
      ConditionLinking: and
    CreateTime: 2018-03-26 19:15:51
    EntityID: Transition-bbe2363e064615326c8683d97cb10da4
    ID: '8'
    Name: 'Digicam :: Order Request :: Sent'
