---
- ChangeBy: '2'
  ChangeTime: 2018-03-25 18:40:55
  Comment: default merged notification to customer
  CreateBy: '1'
  CreateTime: 2018-03-24 14:55:46
  Data:
    AgentEnabledByDefault:
    - Email
    ArticleAttachmentInclude:
    - '0'
    Events:
    - TicketStateUpdate
    IsVisibleForCustomer:
    - '1'
    LanguageID:
    - en
    Recipients:
    - Customer
    StateID:
    - '9'
    TransportEmailTemplate:
    - Default
    Transports:
    - Email
    VisibleForAgent:
    - '0'
  ID: '18'
  Message:
    en:
      Body: 'Dear &lt;OTRS_CUSTOMER_REALNAME&gt;,<br />

        <br />

        we want to inform you, that your ticket with the case number &lt;OTRS_TICKET_TicketNumber&gt;
        has been merged.<br />

        <br />

        <br />

        Kind regards,<br />

        Support - Mayer GmbH'
      ContentType: text/html
      Subject: Ticket merged '<OTRS_TICKET_Title>'
  Name: Ticket merged
  ValidID: '1'
