---
- ChangeBy: '2'
  ChangeTime: 2018-03-25 18:41:01
  Comment: default pending auto close notification to customer
  CreateBy: '1'
  CreateTime: 2018-03-24 14:55:47
  Data:
    AgentEnabledByDefault:
    - Email
    ArticleAttachmentInclude:
    - '0'
    Events:
    - TicketStateUpdate
    IsVisibleForCustomer:
    - '1'
    LanguageID:
    - en
    Recipients:
    - Customer
    StateID:
    - '7'
    - '8'
    TransportEmailTemplate:
    - Default
    Transports:
    - Email
    VisibleForAgent:
    - '0'
  ID: '19'
  Message:
    en:
      Body: 'Dear &lt;OTRS_CUSTOMER_REALNAME&gt;,<br />

        <br />

        your ticket with the case number &lt;OTRS_TICKET_TicketNumber&gt; has been
        changed into pending state.<br />

        If you have don''t have anymore questions the ticket will be closed within
        X days.<br />

        <br />

        We hope to have informed you sufficiently, otherwise please respond to this
        message.<br />

        <br />

        Kind regards,<br />

        Support - Mayer GmbH'
      ContentType: text/html
      Subject: Ticket pending close '<OTRS_TICKET_Title>'
  Name: Ticket pending auto close
  ValidID: '1'
