---
DefaultValue: ''
Link: ''
LinkPreview: ''
PossibleNone: '0'
PossibleValues:  { 
    DACH: 'DACH', 
    BENELUX: 'Benelux', 
    NAM: 'North America', 
    LATAM: 'Latin America',
    EUROPE: 'Europe',
    AMERICA: 'America',
    WORLDWIDE: 'Worldwide',
    'Digicam': 'Digicam', 
    'Medoptics': 'Medoptics', 
    'IntelliEyes DACH': 'IntelliEyes DACH', 
    'IntelliEyes CHINA': 'IntelliEyes CHINA'
    }
TranslatableValues: '0'
TreeView: '0'
