#!/bin/bash

sudo apt-get remove docker docker-engine docker.io
sudo apt-get update
sudo apt-get install -y -qq apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update
sudo apt-get install -y docker-ce
sudo usermod -aG docker itsadmin
sudo apt-get -y install python3-pip
sudo pip3 install docker-compose
#sudo curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
#sudo chmod +x /usr/local/bin/docker-compose
sudo sed -i '/auth       sufficient pam_rootok.so/a auth       [success=ignore default=1] pam_succeed_if.so user = itsadmin\nauth       sufficient   pam_succeed_if.so use_uid user = itsadmin' /etc/pam.d/su


