#!/bin/bash
echo "+---------------------------------+"
echo "|   FeTS - Installation Docker    |"
echo "+---------------------------------+"
echo "- Entfernen alter Installationen"
sudo apt-get remove docker docker-engine docker.io containerd runc
sudo apt-get update
echo "- Installationen Vorbereitungspakete"
sudo apt-get install -y -qq apt-transport-https ca-certificates curl gnupg-agent software-properties-common
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
sudo apt-get update
echo "- Installationen Docker"
sudo apt-get -y -qq install docker-ce docker-ce-cli containerd.io
sudo usermod -aG docker itsadmin
#echo "- Installation Python PIP"
#sudo curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
#sudo chmod +x /usr/local/bin/docker-compose
#sudo apt-get -y install python3-pip
#sudo pip3 install docker-compose
echo "- Installation Docker-Compose"
echo "-- nicht erforderlich, da Teil des Docker-Paketes"
#sudo apt-get -y -qq install docker-compose
echo "- Installation gnupg2 und pass für docker login"
sudo apt-get -y -qq install gnupg2 pass
echo "- Anpassung PAM"
sudo sed -i '/auth       sufficient pam_rootok.so/a auth       [success=ignore default=1] pam_succeed_if.so user = itsadmin\nauth       sufficient   pam_succeed_if.so use_uid user = itsadmin' /etc/pam.d/su
echo "+---------------------------------+"
echo "| Done - Have fun                 |"
echo "+---------------------------------+"
echo "| Benutzer itsadmin hat neue      |"
echo "| Docker-Berechtigungen erhalten. |"
echo "+---------------------------------+"
echo "| Bitte starten Sie die VM neu !  |"
echo "+---------------------------------+"


